### ISSUE TITLE
@producer decorator is not working on a function without @consumer decorator

### ISSUE THREAD

**Issue by davorrunje** [airtai/fastkafka#496]
Why is this test failing?

```python
import asyncio
from pydantic import BaseModel, Field, NonNegativeFloat

from faststream import FastStream, Logger
from faststream.kafka import KafkaBroker, TestKafkaBroker

class Data(BaseModel):
    data: NonNegativeFloat = Field(
        ..., examples=[0.5], description="Float data example"
    )

broker = KafkaBroker("localhost:9092")
app = FastStream(broker)

@broker.publisher("input_data")
async def to_input_data(msg: Data) -> Data:
    # logger.info(f"to_input_data({msg=}, {logger=})")
    return Data(data=msg.data+5.0)

@broker.subscriber("input_data")
async def on_input_data(msg: Data, logger: Logger):
    logger.info(f"on_input_data({msg=}, {logger=})")


import pytest

@pytest.mark.asyncio
async def test_passing():
    async with TestKafkaBroker(broker) as tester_broker:

        await broker.publish(Data(data=5.2), "input_data")

        on_input_data.mock.assert_called()

@pytest.mark.asyncio
async def test_failing():
    async with TestKafkaBroker(broker) as tester_broker:

        await to_input_data(Data(data=0.2))

        # Why is this failing?
        on_input_data.mock.assert_called()

```

**Comment by Lancetnik** [comment]
I suppose we shouldn't support this behavior cuz it is a little implicit than [direct producer call](https://github.com/airtai/fastkafka/blob/FastStream/examples/e02_3_basic_publisher.py#L13) and [wrapping the same function](https://github.com/airtai/fastkafka/blob/FastStream/examples/e02_2_basic_publisher.py#L11)

Also we have a big troubles with this feature implementation cuz we doesn't patch an original function behavior at all for now.

**Comment by davorrunje** [comment]
If this is too difficult to implement, we can live with it. However, we should somehow notify the user that we do not support this usage of the producer decorator. I would either use logger.warning or raise a NotImplemented exception in such cases. How difficult is it to add a logger message or exception in such case?

**Comment by Lancetnik** [comment]
https://github.com/airtai/fastkafka/blob/FastStream/faststream/broker/wrapper.py#L90

No way for now, it is another library responsibility

**Comment by Lancetnik** [comment]
@davorrunje 
Yes, I'm sorry about a wrong Issue answer: it's not very convenient to work from the phone

Regarding the warning when calling functions: I deliberately leave the functions wrapped by our decorators unchanged. This is a common use case when testing HTTP frameworks: test handlers as if they were regular functions. Therefore, I do not modify them with any side effects (like publishing or warnings).

`publisher` decorator works only on functions that are already wrapped by the `subscriber` - thus the user creates an obvious data pipeline unit.

It seems to me that the reason why you are trying to send a message by calling a wrapped function is just a habit from FastKafka. I assume that new users will not expect this behavior (because it is not entirely obvious), especially if they do not find such example in the documentation.

I think it will be enough to display only the correct examples in the documentation, and also indicate that the framed functions do not have side effects.

If you want to add a warning or modify the function with some additional behavior, you can do it [here](https://github.com/airtai/fastkafka/blob/FastStream/faststream/broker/wrapper.py#L72), but I don't think it's necessary

**Comment by davorrunje** [comment]
Thanx for the explanation. I'll close the issue now. Let's see if this is a problem in practice or not before implementing enything.

**Comment by 4ydan** [comment]
So is it still not possible to only publish messages. I have these FastAPI endpoints which publish messages to a stream. Is there any way to do this, without subscribing.
